services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: type_xi
      POSTGRES_DB: auditd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/18/docker
volumes:
  postgres_data:
  