// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, api_key, hmac_secret)
VALUES ($1, $2, $3)
RETURNING id, name, api_key, hmac_secret, active, created_at
`

type CreateTenantParams struct {
	Name       string `json:"name"`
	ApiKey     string `json:"api_key"`
	HmacSecret string `json:"hmac_secret"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.ApiKey, arg.HmacSecret)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.HmacSecret,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, tenant_id, actor_id, actor_type, action, resource_type, resource_id, metadata, timestamp, prev_hash, hash, created_at
FROM audit_events
WHERE id = $1 AND tenant_id = $2
`

type GetEventByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.ID, arg.TenantID)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.Timestamp,
		&i.PrevHash,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getLastEventHash = `-- name: GetLastEventHash :one
SELECT hash
FROM audit_events
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastEventHash(ctx context.Context, tenantID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLastEventHash, tenantID)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const getTenantByAPIKey = `-- name: GetTenantByAPIKey :one
SELECT id, name, hmac_secret, active
FROM tenants
WHERE api_key = $1 AND active = TRUE
`

type GetTenantByAPIKeyRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	HmacSecret string      `json:"hmac_secret"`
	Active     pgtype.Bool `json:"active"`
}

func (q *Queries) GetTenantByAPIKey(ctx context.Context, apiKey string) (GetTenantByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKey, apiKey)
	var i GetTenantByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HmacSecret,
		&i.Active,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO audit_events (
    id, tenant_id, actor_id, actor_type, action,
    resource_type, resource_id, metadata,
    timestamp, created_at, prev_hash, hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id
`

type InsertEventParams struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActorID      string             `json:"actor_id"`
	ActorType    string             `json:"actor_type"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PrevHash     string             `json:"prev_hash"`
	Hash         string             `json:"hash"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.Timestamp,
		arg.CreatedAt,
		arg.PrevHash,
		arg.Hash,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listAllEventsOrdered = `-- name: ListAllEventsOrdered :many
SELECT id, tenant_id, actor_id, actor_type, action, resource_type, resource_id, metadata, timestamp, prev_hash, hash, created_at
FROM audit_events
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAllEventsOrdered(ctx context.Context, tenantID pgtype.UUID) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAllEventsOrdered, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.Timestamp,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, tenant_id, actor_id, actor_type, action, resource_type, resource_id, metadata, timestamp, prev_hash, hash, created_at
FROM audit_events
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.Timestamp,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsFilered = `-- name: ListEventsFilered :many
SELECT id, tenant_id, actor_id, actor_type, action, resource_type, resource_id, metadata, timestamp, prev_hash, hash, created_at
FROM audit_events
where tenant_id = $1
AND ($2::TEXT IS NULL OR actor_id = $2)
AND ($3::TEXT IS NULL OR action = $3)
AND ($4::TEXT IS NULL OR resource_type = $4)
AND ($5::TEXT IS NULL OR resource_id = $5)
AND ($6::timestamptz IS NULL OR timestamp >= $6)
AND ($7::timestamptz IS NULL OR timestamp <= $7)
ORDER BY timestamp DESC
LIMIT $9 
OFFSET $8
`

type ListEventsFileredParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActorID      string      `json:"actor_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	StartTime    interface{} `json:"start_time"`
	EndTime      interface{} `json:"end_time"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

func (q *Queries) ListEventsFilered(ctx context.Context, arg ListEventsFileredParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listEventsFilered,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.StartTime,
		arg.EndTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.Timestamp,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
