// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActorID      string             `json:"actor_id"`
	ActorType    string             `json:"actor_type"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	PrevHash     string             `json:"prev_hash"`
	Hash         string             `json:"hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	ApiKey     string             `json:"api_key"`
	HmacSecret string             `json:"hmac_secret"`
	Active     pgtype.Bool        `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
